AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TodoListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: it.nicolacorvo.TODO_list.StreamLambdaHandler
      Runtime: java21
      CodeUri: .
      MemorySize: 1024
      Timeout: 30
      Policies: AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY